### ISSUE TITLE
Warning: Failed prop type: c: prop type `size` is invalid;

### ISSUE THREAD

**Issue by boyuanx** [stanleyxu2005/react-checkmark#4]
When using Checkmark as:
```<Checkmark size="xxLarge" />```
or 
```<Checkmark size={96} />```

I get the following error:
```
Warning: Failed prop type: c: prop type `size` is invalid; it must be a function, usually from the `prop-types` package, but received `number`.
```

**Comment by stanleyxu2005** [comment]
Hi @boyuanx. Probably the fix can get rid off the annoying warning. Check with v1.3.0

**Comment by boyuanx** [comment]
@stanleyxu2005 I am still getting the same error in `v1.3.0` unfortunately.

**Comment by conioX** [comment]
same with me still getting error already update to v1.3.0

**Comment by stanleyxu2005** [comment]
Create you @conioX @boyuanx give an example on Codepen that I can test with?

**Comment by charan1973** [comment]
Here's a code sandbox link - https://codesandbox.io/s/musing-buck-hr4b4?file=/src/App.js
Check the console once you're there.

**Comment by stanleyxu2005** [comment]
I acknowledged this issue. In `v1.4.0`, you need to change number size to string size. For example `size={192}` now needs to be `size='192px'`. This solves the problem.

**Comment by charan1973** [comment]
> I acknowledged this issue. In `v1.4.0`, you need to change number size to string size. For example `size={192}` now needs to be `size='192px'`. This solves the problem. @boyuanx @charan1973 @ghost

I'll use the string size. Thank you for the fix.
